version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'AAAAAAAAAAAAAA'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'AAAAAAAAAAAAAA'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
#    volumes:
#      - 'sail-mysql:/var/lib/mysql'
#      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
#    networks:
#      - sail
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-pAAAAAAAAAAAAAA" ]
      retries: 3
      timeout: 5s
